version: '2'

services:
    attacker:
        build: ./webrecorder
        command: python /code/attacker_server.py
        depends_on:
            - app

        volumes:
            - ../:/code/
        ports:
            - "8090:8090"

        networks:
          default:
            aliases:
             - attacker.test
