version: '2'

services:
    app:
        volumes:
            - ../archive_server_overlays/:/overlays/
            - ../archive_server_overlays/archive_server_templates/:/code/archive_server_templates/
        environment:
            WR_TEMPLATE_PKG: archive_server_templates
            WR_USER_CONFIG: /overlays/user_config.yml

        command: bash /overlays/init_app_server.sh

    attacker:
        build: ./webrecorder
        command: python /code/archive_server_overlays/attacker_server.py
        depends_on:
            - app

        volumes:
            - ../:/code/
        ports:
            - "8090:8090"

        networks:
          default:
            aliases:
             - attacker.test
