version: '2'

services:
    app:
        volumes:
            - ../../support_files/:/support_files/
        environment:
            WR_TEMPLATE_PKG: support_files.archive_server_templates
            WR_USER_CONFIG: /support_files/user_config.yml

        command: bash /support_files/init_app_server.sh

    attacker:
        build: ./webrecorder
        command: python /support_files/attacker_server.py
        depends_on:
            - app

        volumes:
            - ../../support_files/:/support_files/
            - ../../challenges/:/challenges/
        ports:
            - "8090:8090"

        networks:
          default:
            aliases:
             - attacker.test
