version: '2'

services:
    app:
        volumes:
            - ${WARCGAMES_ROOT}/support_files/:/support_files/
        command: bash /support_files/init_app_server.sh

    attacker:
        build: ./webrecorder
        command: python /support_files/attacker_server.py
        depends_on:
            - app

        volumes:
            - ${WARCGAMES_ROOT}/support_files/:/support_files/
            - ${WARCGAMES_ROOT}/challenges/:/challenges/
        ports:
            - "8090:8090"

        networks:
          default:
            aliases:
             - attacker.test
